### ISSUE TITLE
Warhol web data not being pulled into dashboard

### ISSUE THREAD

**Issue by staticmade** [CMP-Studio/Dashboard#10]
It appears that Warhol GA data isn't being pulled into the dashboard. Image:

![screenshot 2016-04-04 11 15 23](https://cloud.githubusercontent.com/assets/3757910/14252735/a04df1e2-fa56-11e5-8bc5-c5558abc61cc.png)

**Comment by drewmcd621** [comment]
I looked at the error logs, the account that grabs the GA data appears to have been removed from the Warhol GA account on or before 3-1-16.  I can't add that account to the Warhol's GA (As I do not have permissions).
