### ISSUE TITLE
Icon scaling issues in Safari

### ISSUE THREAD

**Issue by workergnome** [CMP-Studio/Dashboard#6]
When the dashboard is loaded in Safari, there are issues with scaling at particular sizes.  See attached screen shot

![screen shot 2015-09-24 at 11 40 20 am](https://cloud.githubusercontent.com/assets/34536/10078109/505bb68e-62b1-11e5-936c-a3dc544539e5.png)

**Comment by drewmcd621** [comment]
I believe I have fixed the issue but I'm using a Safari emulator, if you could check on the native browser to be sure it is fixed I would appreciate it.

**Comment by workergnome** [comment]
Looks fixed on my end.  Thanks!

—
David Newbury
(773) 547-2272
david.newbury@gmail.com
